apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: udphpgqq2-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:c972328555c2ec7c954b84dfe4cebf64c30a39d6@sha256:32e0af362fb3b26d6ef028e257fc047db9b862476d8b7d1f7e77013d4db937ec
          name: container-image
